# Index
index:
  path: /
  controller: App\Controller\IndexController::index

product:
  path: /product
  controller: App\Controller\ProductController::index


# Admin
# Security
security.admin.login:
  path: /login
  controller: App\Controller\Admin\SecurityController::login

security.admin.logout:
    path: /logout
    methods: GET

security.admin.create:
    path: /admin/create-admin
    controller: App\Controller\Admin\SecurityController::create

# Product
admin.product.index:
  path: /admin
  controller: App\Controller\Admin\AdminProductController::index

admin.product.create:
  path: /admin/create
  controller: App\Controller\Admin\AdminProductController::create

admin.product.edit:
  path: /admin/{id}
  controller: App\Controller\Admin\AdminProductController::edit
  methods: GET|POST

admin.product.delete:
  path: /admin/{id}
  controller: App\Controller\Admin\AdminProductController::delete
  methods: DELETE